---
outdir_dir: "."
title: "RNotebookExample"
output: html_document
---

```{r load-data, message=FALSE} 
library(tidyverse)
library(kableExtra)
library(rmarkdown)
library(ggpubr)

pop_data <- read_csv("data/gapminder_data.csv")

# create a table with data from European countries in 2007 and ordered by life expectancy

euro_data_tbl <- pop_data %>% 
  filter(continent == "Europe" & year == 2007) %>% 
  select(-continent, -year) %>% 
  arrange(desc(lifeExp)) %>% 
  rename(Country = country, "Population Size" = pop, "Life Expectancy" = lifeExp, GDP = gdpPercap)


```

The results in euro_data_tbl are presented below:
```{r kbl, message=FALSE}

euro_data_tbl %>% 
  kbl() %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

```

better way to display long tables

```{r paged-table}

paged_table(euro_data_tbl)
```

#inserting images

```{r}
euro_data_fig <- pop_data %>% 
  filter(continent == "Europe") %>% 
  mutate(year = as.factor(year))

euro_plot <- euro_data_fig %>% 
  ggplot(aes(x=year, y=lifeExp)) + 
  geom_violin() +
  stat_summary(fun = median, geom = "point")

euro_plot

uk_data_fig <- pop_data %>% 
  filter(country == "United Kingdom") %>% 
  mutate(year = as.factor(year))

uk_plot <- uk_data_fig %>% 
  ggplot(aes(x=year, y=lifeExp)) +
  geom_point()

uk_plot

ggarrange(euro_plot, uk_plot, ncol = 2, nrow = 1, labels = "AUTO")



```

 https://github.com/MajaCN/first-notebook.git

